name: codenarc-new

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release
    paths:
      - '**.groovy'

jobs:
  codenarc:
    name: codenarc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Run codenarc
        uses: jemersonmaia/codenarc-action@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          rulesetfiles: 'file:codenarcrules.xml'
          
      - name: Run codenarc
        uses: asaasdev/codenarc-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          rulesetfiles: 'file:codenarcrules.xml'
